name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed files
      id: changed-files
      run: |
        echo "Base commit: ${{ github.event.before }}"
        echo "Head commit: ${{ github.sha }}"
        echo "Changed files:"
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "::set-output name=changed_files::$changed_files"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Replace with the actual dependencies installation command if needed

    - name: Run pytest
      run: |
        if [ -z "${{ steps.changed-files.outputs.changed_files }}" ]; then
          echo "No changed files. Skipping tests."
        else
          echo "Changed files: ${{ steps.changed-files.outputs.changed_files }}"
          # Adjust the following line based on your project's naming convention
          # This assumes that test files start with "test_" and have the ".py" extension
          pytest ${{ steps.changed-files.outputs.changed_files//src\//tests/}}
        fi


