name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed files
      id: changed-files
      run: |
        echo "Base commit: ${{ github.event.before }}"
        echo "Head commit: ${{ github.sha }}"
        echo "Changed files:"
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
        echo "::set-output name=changed_files::$changed_files"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Replace with the actual dependencies installation command if needed
    - name: Run pytest
      run: |
       changed_files=$(git show --name-only --oneline ${{ github.event.before }}..${{ github.sha }} | tail -n +2)
       echo "Changed files: $changed_files"
       if [ -z "$changed_files" ]; then
       echo "No changed files. Skipping tests."
       else
       pytest $(echo "$changed_files" | sed 's|^src/|tests/|')
       fi



