name: Dynamic Test Workflow

on:
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine and run affected tests
      run: |
        # Determine the affected files
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})


        # Run tests for each affected test file
        for file in $changed_files; do
        # Check if the file is a test file
            if [[ $file == *"tests/"* && $file == *"test_"* && $file == *".py" ]]; then
            echo "Running tests for $file"
              pytest -v "$file"
                fi
             done
