name: Dynamic Pytest Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust based on your project setup

    - name: Run tests
      run: pytest

    - name: Check for changes in files
      id: check_changes
      run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" >> $GITHUB_ENV

    - name: Filter tests based on changes
      id: filter_tests
      run: |
        # Modify the command below based on your project structure
        echo "AFFECTED_FILES=$(echo "${CHANGED_FILES}" | grep '^src/.*\.py$\|^tests/.*\.py$' || true)" >> $GITHUB_ENV

    - name: Run only affected tests
      if: env.AFFECTED_FILES != ''
      run: |
        # Install pytest-xdist for parallel test execution
        pip install pytest-xdist

        # Run tests in parallel for affected files
        pytest -k "${AFFECTED_FILES}" -n auto
