name: Dynamic Test Workflow

on:
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine affected files
      id: affected-files
      run: |
        echo "Determine affected files"
        base_commit=$(git rev-parse HEAD^)
        echo "::set-output name=files::$(git diff $base_commit HEAD --name-only)"

    - name: Print debug information
      run: |
        echo "Changed files:"
        echo "${{ steps.affected-files.outputs.files }}"

    - name: Run tests for affected files
      run: |
        for file in ${{ steps.affected-files.outputs.files }}; do
          # Check if the file is a test file
          if [[ $file == *"tests/"* && $file == *"test_"* && $file == *".py" ]]; then
            pytest -v "$file"
          fi
        done

