on:
  pull_request:
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Determine affected files
      id: determine-affected-files
      run: |
       git diff --name-only ${{ github.event.before }} ${{ github.sha }}

    - name: Run affected tests
      run: |
        # Use the output variable from the previous step
        for file in ${{ steps.determine-affected-files.outputs.files }}; do
          if [[ $file == *"tests/"* && $file == *"test_"* && $file == *".py" ]]; then
            pytest "$file"
          fi
        done

